version: "3.6"
services:
  php:
    image: php:7
    command: php -S 0.0.0.0:3000 /app/index.php
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  composer:
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app
